/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package for_log_in;

import user.*;
import config.dbConnector;
import for_log_in.admincustomers;
import for_log_in.admindashboard;
import javax.swing.JOptionPane;

/**
 *
 * @author DERECHO
 */
public class adoptionapplicationforcustomer extends javax.swing.JFrame {

     private dbConnector dbc;
     
    public adoptionapplicationforcustomer() {
        initComponents();
         dbc = new dbConnector();
    }
    
     public String action = "";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        gen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        c_label = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ag = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        con = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerpanel.setBackground(new java.awt.Color(255, 255, 255));
        customerpanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(null);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel1.add(gen);
        gen.setBounds(460, 60, 80, 26);

        jLabel7.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 40, 50, 20);

        c_label.setBackground(new java.awt.Color(255, 255, 255));
        c_label.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        c_label.setText("Add");
        c_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_labelActionPerformed(evt);
            }
        });
        jPanel1.add(c_label);
        c_label.setBounds(790, 570, 80, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25-wall.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, -20, 500, 340);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setLayout(null);

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        jPanel2.add(ema);
        ema.setBounds(30, 50, 350, 50);

        jLabel2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel2.setText("Email");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 50, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 390, 410, 150);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setLayout(null);

        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        jPanel3.add(ag);
        ag.setBounds(20, 140, 370, 50);

        jLabel9.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel9.setText("Age");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 120, 100, 20);
        jPanel3.add(nm);
        nm.setBounds(20, 40, 370, 50);

        jLabel10.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel10.setText("Name");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 20, 100, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 50, 410, 230);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(null);

        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel4.add(con);
        con.setBounds(30, 40, 360, 50);

        jLabel11.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel11.setText("Contact");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 20, 50, 20);
        jPanel4.add(add);
        add.setBounds(30, 150, 360, 50);

        jLabel12.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel12.setText("Address");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 130, 50, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 310, 410, 230);

        customerpanel.add(jPanel1);
        jPanel1.setBounds(20, 40, 940, 640);

        jLabel19.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-arrow-back-20.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        customerpanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaActionPerformed

    private void c_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_labelActionPerformed
     String name = nm.getText();
        String age = ag.getText();
        String gender = gen.getSelectedItem().toString();
        String contact = con.getText();
        String address = add.getText();
        String email = ema.getText();
        
        if (name.isEmpty() || age.isEmpty() || contact.isEmpty() || address.isEmpty() || email.isEmpty() || gen.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                dbc.insertData("INSERT INTO tbl_customers(c_name, c_age, c_gender, c_contact, c_address, c_email) VALUES('" + name + "', '" + age + "', '" + gender + "', '" + contact + "', '" + address + "', '" + email + "')");
                JOptionPane.showMessageDialog(null, "Successfully Saved");
                
                // After saving, update the admincustomers table
                admincustomers admin = new admincustomers();
                admin.setVisible(true);
                this.dispose();
                
            } catch (Exception e) {
                System.out.println("Saving Data Failed: " + e);
            }
        }                                      

    }//GEN-LAST:event_c_labelActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        admincustomers up = new admincustomers();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adoptionapplicationforcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField ag;
    private javax.swing.JButton c_label;
    private javax.swing.JTextField con;
    private javax.swing.JPanel customerpanel;
    private javax.swing.JTextField ema;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nm;
    // End of variables declaration//GEN-END:variables
}
