/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package for_log_in;

import user.*;
import config.dbConnector;
import for_log_in.admincustomers;
import for_log_in.admindashboard;
import javax.swing.JOptionPane;

/**
 *
 * @author DERECHO
 */
public class adoptionapplicationforcustomer extends javax.swing.JFrame {

     private dbConnector dbc;
     
    public adoptionapplicationforcustomer() {
        initComponents();
         dbc = new dbConnector();
    }
    
     public String action = "";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        con = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        gen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        c_label = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerpanel.setBackground(new java.awt.Color(255, 255, 255));
        customerpanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 50, 20);
        jPanel1.add(nm);
        nm.setBounds(30, 40, 150, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 50, 20);

        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        jPanel1.add(ag);
        ag.setBounds(30, 140, 150, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Contact");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 220, 50, 20);

        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel1.add(con);
        con.setBounds(30, 240, 150, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 320, 50, 20);
        jPanel1.add(add);
        add.setBounds(30, 340, 150, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 430, 50, 20);

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        jPanel1.add(ema);
        ema.setBounds(30, 450, 150, 40);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel1.add(gen);
        gen.setBounds(240, 50, 80, 26);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 30, 50, 20);

        c_label.setBackground(new java.awt.Color(255, 255, 255));
        c_label.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        c_label.setText("Add");
        c_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_labelActionPerformed(evt);
            }
        });
        jPanel1.add(c_label);
        c_label.setBounds(250, 470, 80, 20);

        customerpanel.add(jPanel1);
        jPanel1.setBounds(20, 40, 370, 520);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25-wall.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        customerpanel.add(jLabel8);
        jLabel8.setBounds(170, 30, 550, 340);

        jLabel19.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-arrow-back-20.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        customerpanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conActionPerformed

    private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaActionPerformed

    private void c_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_labelActionPerformed
     String name = nm.getText();
        String age = ag.getText();
        String gender = gen.getSelectedItem().toString();
        String contact = con.getText();
        String address = add.getText();
        String email = ema.getText();
        
        if (name.isEmpty() || age.isEmpty() || contact.isEmpty() || address.isEmpty() || email.isEmpty() || gen.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                dbc.insertData("INSERT INTO tbl_customers(c_name, c_age, c_gender, c_contact, c_address, c_email) VALUES('" + name + "', '" + age + "', '" + gender + "', '" + contact + "', '" + address + "', '" + email + "')");
                JOptionPane.showMessageDialog(null, "Successfully Saved");
                
                // After saving, update the admincustomers table
                admincustomers admin = new admincustomers();
                admin.setVisible(true);
                this.dispose();
                
            } catch (Exception e) {
                System.out.println("Saving Data Failed: " + e);
            }
        }                                      

    }//GEN-LAST:event_c_labelActionPerformed

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        admincustomers up = new admincustomers();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adoptionapplicationforcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adoptionapplicationforcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField ag;
    private javax.swing.JButton c_label;
    private javax.swing.JTextField con;
    private javax.swing.JPanel customerpanel;
    private javax.swing.JTextField ema;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nm;
    // End of variables declaration//GEN-END:variables
}
