/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbConnector;
import for_log_in.admincustomers;
import for_log_in.admindashboard;
import for_log_in.foradoptedpet;
import javax.swing.JOptionPane;

/**
 *
 * @author DERECHO
 */
public class adoptionapplication extends javax.swing.JFrame {

     private dbConnector dbc;
     
    public adoptionapplication() {
        initComponents();
         dbc = new dbConnector();
    }
    
     public String action = "";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        br = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c_label = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        genm = new javax.swing.JRadioButton();
        genf = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerpanel.setBackground(new java.awt.Color(255, 255, 255));
        customerpanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 70, 50, 20);

        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        jPanel1.add(nm);
        nm.setBounds(270, 90, 400, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 190, 50, 20);

        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        jPanel1.add(ag);
        ag.setBounds(270, 210, 400, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setText("Breed");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 310, 50, 20);

        br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brActionPerformed(evt);
            }
        });
        jPanel1.add(br);
        br.setBounds(270, 330, 400, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 440, 50, 20);

        c_label.setBackground(new java.awt.Color(255, 255, 255));
        c_label.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        c_label.setText("Add");
        c_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_labelActionPerformed(evt);
            }
        });
        jPanel1.add(c_label);
        c_label.setBounds(580, 470, 80, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25-wall.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, -20, 550, 340);

        genm.setBackground(new java.awt.Color(255, 255, 255));
        genm.setText("Male");
        genm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genmActionPerformed(evt);
            }
        });
        jPanel1.add(genm);
        genm.setBounds(270, 520, 90, 29);

        genf.setBackground(new java.awt.Color(255, 255, 255));
        genf.setText("Female");
        genf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genfActionPerformed(evt);
            }
        });
        jPanel1.add(genf);
        genf.setBounds(270, 470, 90, 29);

        customerpanel.add(jPanel1);
        jPanel1.setBounds(20, 40, 950, 640);

        jLabel19.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-arrow-back-20.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        customerpanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brActionPerformed

    private void c_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_labelActionPerformed
        String name = nm.getText();
        String age = ag.getText();
        String gender = action;
        String breed = br.getText();

        if (name.isEmpty() || age.isEmpty() || breed.isEmpty() || gender.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required");
            }else{
            try {
                dbc.insertData("INSERT INTO tbl_adopted(a_name, a_age,a_gender, a_breed) VALUES('" + name + "', '" + age + "', '" + gender + "', '" + breed + "')");
                JOptionPane.showMessageDialog(null, "Successfully Saved");
                
                userDashboard admin = new userDashboard();
                admin.setVisible(true);
                this.dispose();
            } catch (Exception e) {
                System.out.println("Saving Data Failed: " + e);
            }
        }                                      

    }//GEN-LAST:event_c_labelActionPerformed

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        adoptinfo up = new adoptinfo();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void genfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genfActionPerformed
         action = "Female";
    }//GEN-LAST:event_genfActionPerformed

    private void genmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genmActionPerformed
         action = "Male"; 
    }//GEN-LAST:event_genmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adoptionapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adoptionapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adoptionapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adoptionapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adoptionapplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag;
    private javax.swing.JTextField br;
    private javax.swing.JButton c_label;
    private javax.swing.JPanel customerpanel;
    private javax.swing.JRadioButton genf;
    private javax.swing.JRadioButton genm;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nm;
    // End of variables declaration//GEN-END:variables
}
