/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_pet_adoption;
import for_log_in.*;
/**
 *
 * @author DERECHO
 */
public class Home_pages extends javax.swing.JFrame {

    /**
     * Creates new form Home_pages
     */
    public Home_pages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homedesktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        homedesktop1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel14 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel2.add(jScrollBar1);
        jScrollBar1.setBounds(-3, 320, 640, 10);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel14.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(null);
        jPanel14.add(jPanel4);
        jPanel4.setBounds(8, 12, 140, 70);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(null);
        jPanel14.add(jPanel6);
        jPanel6.setBounds(10, 90, 70, 10);

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setLayout(null);
        jPanel14.add(jPanel7);
        jPanel7.setBounds(140, 90, 10, 10);

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setLayout(null);
        jPanel14.add(jPanel8);
        jPanel8.setBounds(90, 90, 40, 10);

        jPanel2.add(jPanel14);
        jPanel14.setBounds(40, 40, 160, 180);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel15.setForeground(new java.awt.Color(0, 51, 51));
        jPanel15.setLayout(null);
        jPanel2.add(jPanel15);
        jPanel15.setBounds(40, 220, 160, 30);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel16.setForeground(new java.awt.Color(0, 51, 51));
        jPanel16.setLayout(null);
        jPanel2.add(jPanel16);
        jPanel16.setBounds(240, 220, 160, 30);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel17.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setToolTipText("");
        jPanel9.setLayout(null);
        jPanel17.add(jPanel9);
        jPanel9.setBounds(8, 12, 140, 70);

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(null);
        jPanel17.add(jPanel10);
        jPanel10.setBounds(10, 90, 70, 10);

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setLayout(null);
        jPanel17.add(jPanel11);
        jPanel11.setBounds(140, 90, 10, 10);

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setLayout(null);
        jPanel17.add(jPanel12);
        jPanel12.setBounds(90, 90, 40, 10);

        jPanel2.add(jPanel17);
        jPanel17.setBounds(240, 40, 160, 180);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel18.setForeground(new java.awt.Color(0, 51, 51));
        jPanel18.setLayout(null);
        jPanel2.add(jPanel18);
        jPanel18.setBounds(440, 220, 160, 30);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel19.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(0, 51, 51));
        jPanel13.setToolTipText("");
        jPanel13.setLayout(null);
        jPanel19.add(jPanel13);
        jPanel13.setBounds(8, 12, 140, 70);

        jPanel20.setBackground(new java.awt.Color(0, 102, 102));
        jPanel20.setLayout(null);
        jPanel19.add(jPanel20);
        jPanel20.setBounds(10, 90, 70, 10);

        jPanel21.setBackground(new java.awt.Color(0, 51, 51));
        jPanel21.setLayout(null);
        jPanel19.add(jPanel21);
        jPanel21.setBounds(140, 90, 10, 10);

        jPanel22.setBackground(new java.awt.Color(0, 51, 51));
        jPanel22.setLayout(null);
        jPanel19.add(jPanel22);
        jPanel22.setBounds(90, 90, 40, 10);

        jPanel2.add(jPanel19);
        jPanel19.setBounds(440, 40, 160, 180);

        homedesktop1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homedesktop1Layout = new javax.swing.GroupLayout(homedesktop1);
        homedesktop1.setLayout(homedesktop1Layout);
        homedesktop1Layout.setHorizontalGroup(
            homedesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        homedesktop1Layout.setVerticalGroup(
            homedesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel1.add(homedesktop1);
        homedesktop1.setBounds(20, 110, 640, 330);

        jButton1.setFont(new java.awt.Font("Candara", 1, 11)); // NOI18N
        jButton1.setText("Home");
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 70, 70, 23);

        jButton2.setText("Add Pet");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 70, 80, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-users-60.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(600, 60, 60, 50);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-arrow-24.png"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 0, 24, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-x-24.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(656, 0, 30, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 690, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/77281cb6d94e94c2d71bacdba9d74d7f.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-310, -360, 550, 570);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/77281cb6d94e94c2d71bacdba9d74d7f.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-80, 280, 550, 520);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/77281cb6d94e94c2d71bacdba9d74d7f.png"))); // NOI18N
        jLabel10.setText("jLabel1");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(440, 0, 550, 520);

        homedesktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homedesktopLayout = new javax.swing.GroupLayout(homedesktop);
        homedesktop.setLayout(homedesktopLayout);
        homedesktopLayout.setHorizontalGroup(
            homedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        homedesktopLayout.setVerticalGroup(
            homedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homedesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homedesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        logIn up = new logIn();
        homedesktop.add(up).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_pages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_pages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane homedesktop;
    private javax.swing.JDesktopPane homedesktop1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
